services:
  app:
    build: .
    container_name: my_php_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: my_db
      DB_USERNAME: php-crud
      DB_PASSWORD: 123
    networks:
      - appnet

  db:
    image: mysql:9.3.0
    container_name: my_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: php-crud
      MYSQL_PASSWORD: 123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - appnet

volumes:
  mysql_data:

networks:
  appnet:
